# Generated by Django 3.1.1 on 2021-01-08 03:59

import FileApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('fileName', models.CharField(max_length=1023)),
                ('createdDate', models.DateTimeField(auto_now=True)),
                ('Code', models.CharField(default=FileApp.models.random_code, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('image', models.CharField(default='etc', max_length=255)),
                ('Memo', models.CharField(blank=True, max_length=1023)),
            ],
        ),
    ]
