# Generated by Django 3.1.1 on 2021-04-11 15:53

import FileApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('fileName', models.CharField(max_length=1023)),
                ('createdDate', models.DateTimeField(auto_now=True)),
                ('Code', models.CharField(default=FileApp.models.random_code, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('image', models.CharField(default='etc', max_length=255)),
                ('Memo', models.CharField(blank=True, max_length=1023)),
                ('ownerPCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectApp.projects')),
                ('whoIsOwner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('notice', models.CharField(blank=True, max_length=255)),
                ('proj_id', models.ForeignKey(db_column='proj_id', on_delete=django.db.models.deletion.CASCADE, to='ProjectApp.projects')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
