# Generated by Django 3.1.1 on 2021-04-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NodeApp', '0001_initial'),
        ('FileApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='File_Nodes',
            field=models.ManyToManyField(blank=True, related_name='FileNode', to='NodeApp.Nodes'),
        ),
    ]
