# Generated by Django 3.1.1 on 2020-11-09 00:48

import FileApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='Code',
            field=models.CharField(default=FileApp.models.random_code, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
