# Generated by Django 3.1.1 on 2021-01-08 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProjectApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FileApp', '0001_initial'),
        ('NodeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='File_Nodes',
            field=models.ManyToManyField(blank=True, related_name='FileNode', to='NodeApp.Nodes'),
        ),
        migrations.AddField(
            model_name='files',
            name='ownerPCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectApp.projects'),
        ),
        migrations.AddField(
            model_name='files',
            name='whoIsOwner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
