# Generated by Django 3.1.1 on 2021-04-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0002_files_file_nodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='File_Nodes',
        ),
    ]
