# Generated by Django 3.1.1 on 2020-11-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0002_auto_20201109_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='image',
            field=models.CharField(default='etc', max_length=255),
        ),
    ]
