# Generated by Django 3.1.1 on 2021-01-07 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NodeApp', '0001_initial'),
        ('FileApp', '0002_files_file_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='LastFile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='NodeApp.nodes'),
        ),
    ]
