# Generated by Django 3.1.1 on 2021-01-11 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NodeApp', '0002_auto_20210108_1723'),
        ('FileApp', '0003_auto_20210108_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='Last_File',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lastfile', to='NodeApp.nodes'),
        ),
    ]
