# Generated by Django 3.1.1 on 2020-11-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0003_files_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='Memo',
            field=models.CharField(blank=True, max_length=1023),
        ),
    ]
