# Generated by Django 3.1.1 on 2021-01-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0003_files_lastfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='LastFile',
        ),
    ]
