# Generated by Django 3.1.1 on 2021-02-01 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0004_auto_20210114_1921'),
        ('FileApp', '0004_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='proj_id',
            field=models.ForeignKey(db_column='proj_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='ProjectApp.projects'),
            preserve_default=False,
        ),
    ]
