# Generated by Django 3.1.1 on 2021-02-04 10:54

import NodeApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NodeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='filename',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='comment',
            field=models.CharField(blank=True, default='설명을써주세요', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='fileObj',
            field=models.FileField(null=True, upload_to=NodeApp.models.get_file_path),
        ),
    ]
