# Generated by Django 3.1.1 on 2020-10-27 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0001_initial'),
        ('NodeApp', '0002_auto_20201027_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='test')),
            ],
        ),
        migrations.AlterField(
            model_name='nodes',
            name='ownerPCode',
            field=models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, to='ProjectApp.projects'),
        ),
    ]
