# Generated by Django 3.1.1 on 2021-01-18 22:52

import NodeApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NodeApp', '0002_auto_20210108_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='comment',
            field=models.CharField(blank=True, default='설명을써주세요', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='fileObj',
            field=models.FileField(null=True, upload_to=NodeApp.models.get_file_path),
        ),
    ]
