# Generated by Django 3.1.3 on 2021-02-15 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NodeApp', '0002_auto_20210204_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='node_comment',
            name='who_is_mentioned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='who_is_mentioned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='node_comment',
            name='author_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
