# Generated by Django 3.1.3 on 2021-02-18 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NodeApp', '0003_auto_20210215_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node_comment',
            name='node_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_comments', to='NodeApp.nodes'),
        ),
    ]
