# Generated by Django 3.1.1 on 2021-01-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NodeApp', '0003_auto_20210119_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='filename',
            field=models.CharField(max_length=256, null=True, verbose_name='첨부파일명'),
        ),
    ]
