# Generated by Django 3.1.1 on 2020-11-05 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0001_initial'),
        ('NodeApp', '0004_auto_20201027_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='ownerPCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FileApp.files'),
        ),
    ]
