# Generated by Django 3.1.3 on 2021-02-18 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NodeApp', '0004_auto_20210218_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node_comment',
            name='node_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NodeApp.nodes'),
        ),
    ]
