# Generated by Django 3.1.1 on 2020-11-05 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0001_initial'),
        ('ProjectApp', '0002_auto_20201105_1301'),
        ('NodeApp', '0005_auto_20201105_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='ownerFCode',
            field=models.ForeignKey(default=6531164, on_delete=django.db.models.deletion.CASCADE, to='FileApp.files'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nodes',
            name='ownerPCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectApp.projects'),
        ),
    ]
