# Generated by Django 3.1.1 on 2021-01-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NodeApp', '0006_remove_nodes_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='filename',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
