# Generated by Django 3.1.1 on 2020-11-13 18:52

import NodeApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NodeApp', '0006_auto_20201105_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='Code',
            field=models.CharField(default=NodeApp.models.random_code, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
