# Generated by Django 3.1.1 on 2020-11-13 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NodeApp', '0007_auto_20201114_0352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestNode',
        ),
    ]
