# Generated by Django 3.1.1 on 2020-11-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NodeApp', '0008_delete_testnode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodes',
            options={'ordering': ['ownerPCode', 'createdDate']},
        ),
    ]
