# Generated by Django 3.1.1 on 2020-11-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NodeApp', '0008_delete_testnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nodes',
            name='description',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='nodes',
            name='nodeName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
