# Generated by Django 3.1.1 on 2020-11-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.TextField(blank=True),
        ),
    ]
