# Generated by Django 3.1.1 on 2021-05-02 21:57

import UserApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles\\default_profile.png', upload_to=UserApp.models.user_path),
        ),
    ]
