# Generated by Django 3.1.1 on 2021-01-08 08:48

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
