# Generated by Django 3.1.1 on 2021-06-28 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_dashboard_user'),
        ('UserApp', '0002_auto_20210502_2157'),
    ]

    operations = [
    ]
