# Generated by Django 3.1.1 on 2020-11-04 12:24

import UserApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_profile_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=UserApp.models.user_path),
        ),
    ]
