# Generated by Django 3.1.1 on 2020-11-13 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0002_auto_20201105_1301'),
        ('UserApp', '0003_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileIncludeproj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('includeproj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectApp.projects')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='includeproj',
            field=models.ManyToManyField(through='UserApp.ProfileIncludeproj', to='ProjectApp.Projects'),
        ),
    ]
