# Generated by Django 3.1.1 on 2021-01-08 09:26

import UserApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_auto_20210108_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='.static_root\\MainApp\\image\\default_profile.png', upload_to=UserApp.models.user_path),
        ),
    ]
