# Generated by Django 3.1.1 on 2021-01-14 07:41

import UserApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_auto_20210108_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='MainApp\\image\\default_profile.png', upload_to=UserApp.models.user_path),
        ),
    ]
