# Generated by Django 3.1.3 on 2021-02-04 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_profile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
    ]
