# Generated by Django 3.1.1 on 2020-11-25 11:08

import ProjectApp.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(default=ProjectApp.models.random_code, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 25, 20, 8, 26, 364956), null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=20000)),
                ('whoIsOwner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
