# Generated by Django 3.1.3 on 2020-11-25 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 26, 0, 6, 35, 441293), null=True),
        ),
    ]
