# Generated by Django 3.1.1 on 2021-01-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='likeornot',
        ),
    ]
