# Generated by Django 3.1.1 on 2020-11-05 04:01

import ProjectApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Code',
            field=models.CharField(default=ProjectApp.models.random_code, max_length=255, unique=True),
        ),
    ]
