# Generated by Django 3.1.1 on 2021-04-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NodeApp', '0002_remove_nodes_ownerfcode'),
        ('ProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Proj_Nodes',
            field=models.ManyToManyField(blank=True, related_name='ProjNode', to='NodeApp.Nodes'),
        ),
    ]
