# Generated by Django 3.1.1 on 2020-11-26 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0002_auto_20201125_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 26, 20, 4, 13, 555156), null=True),
        ),
    ]
