# Generated by Django 3.1.1 on 2020-12-22 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectApp', '0002_auto_20201219_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='whoIsOwner',
        ),
        migrations.AddField(
            model_name='projects',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
