# Generated by Django 3.1.3 on 2020-11-21 03:01

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0002_auto_20201105_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='projects',
            name='due_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 21, 12, 0, 33, 102177)),
        ),
    ]
