# Generated by Django 3.1.1 on 2021-01-19 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0002_auto_20210114_0936'),
        ('ProjectApp', '0002_remove_projects_likeornot'),
    ]

    operations = [
    ]
