# Generated by Django 3.1.1 on 2020-11-26 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0003_auto_20201126_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 26, 19, 57, 53, 100819), null=True),
        ),
    ]
