# Generated by Django 3.1.3 on 2020-11-24 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0003_auto_20201121_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 25, 3, 7, 36, 230736)),
        ),
    ]
