# Generated by Django 3.1.1 on 2020-12-26 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectApp', '0004_auto_20201224_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='members',
        ),
        migrations.AddField(
            model_name='projects',
            name='liked_members',
            field=models.ManyToManyField(blank=True, related_name='Joined_Liked_Projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projects',
            name='unliked_members',
            field=models.ManyToManyField(blank=True, related_name='Joined_Unliked_Projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
