# Generated by Django 3.1.3 on 2020-11-24 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0004_auto_20201125_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 25, 3, 8, 51, 724214), null=True),
        ),
    ]
