# Generated by Django 3.1.1 on 2020-11-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0005_auto_20201125_0308'),
        ('ProjectApp', '0003_auto_20201125_1738'),
    ]

    operations = [
    ]
