# Generated by Django 3.1.1 on 2020-11-25 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0006_merge_20201125_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 25, 18, 5, 23, 622348), null=True),
        ),
    ]
