# Generated by Django 3.1.1 on 2020-11-25 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0007_auto_20201125_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 25, 19, 51, 57, 890772), null=True),
        ),
    ]
